spring.application.name=CurrencyConverter
#currency.api.key=b294376a4bbdfceafc0082642ea9c982
#currency.api.url=https://api.exchangeratesapi.io/v1
currency.api.key=7f720a38bd3e46e389b06f83554940bc
currency.api.url=https://openexchangerates.org/api
server.error.whitelabel.enabled=false
server.error.include-message=always
